---
title: "Plot brain age predictions"
output:
  html_document:
    df_print: paged
params:
  names:
    - "EDIS"
    - "SLABS"
    - "GUSTO"
---

```{r}
names <- params$names
source("utils.R")
source("Study.R")
for (name in names) {
  source(paste0(name, ".R"))
}
```

# Plots

```{r}
for (name in names) {
  study <- Study(name)
  plot_predictions(study, ext = "_pretrained")
  plot_predictions(study, ext = "_finetuned")
  compare_predictions(study@data_T1, "_pretrained", "_finetuned")
    
  # longitudinal info
  if (study@is_longitudinal) {
    print("# of scans:")
    print(nrow(study@data_T1))
    print("follow-up time:")
    follow_up_time(study@data_T1)
  }
  
  # variance by age for GUSTO
  if(is(study, "GUSTO")) {
    vars <- c()
    for (age in c(4.5, 6, 7.5, 10.5)) {
      tmp <- subset(study@data_T1, age_category == age)
      vars <- c(vars, var(tmp$pred_age_finetuned))
    }
    
    plot(c(4.5, 6, 7.5, 10.5), vars,
      pch = 19, col = "blue", cex.lab = 1.25,
      xlab = "Chronological Age (years)",
      ylab = "Variance of Predicted Ages"
    )
  }
}
```
